"""
Markdown output writer for Obsidian-compatible vaults.

Produces a single .md file per meeting containing YAML frontmatter
(for Obsidian Dataview queries), the AI-generated summary, and
optionally the full timestamped transcript.

File naming uses the configured template with date and a slug
derived from the meeting title.
"""

import logging
import os
import time
from pathlib import Path

import yaml as _yaml
from slugify import slugify

from src.summariser import MeetingSummary
from src.transcriber import Transcript
from src.utils.config import MarkdownConfig

logger = logging.getLogger(__name__)


class MarkdownWriter:
    """Writes meeting output to an Obsidian-compatible Markdown vault."""

    def __init__(self, config: MarkdownConfig):
        self._config = config

    def write(
        self,
        summary: MeetingSummary,
        transcript: Transcript,
        started_at: float,
        duration_seconds: float,
    ) -> Path:
        """
        Write the meeting summary and transcript to a .md file.

        Returns the path to the created file.
        """
        vault_path = Path(self._config.vault_path)
        os.makedirs(vault_path, exist_ok=True)

        # Build the filename from the configured template.
        date_str = time.strftime("%Y-%m-%d", time.localtime(started_at))
        time_str = time.strftime("%H-%M", time.localtime(started_at))
        title_slug = slugify(summary.title, max_length=60)

        filename = self._config.filename_template.format(
            date=date_str,
            time=time_str,
            slug=title_slug or "meeting",
        )

        # Sanitize filename to prevent directory traversal.
        filename = filename.replace("/", "_").replace("\\", "_").lstrip(".")
        filepath = (vault_path / filename).resolve()
        if not filepath.is_relative_to(vault_path.resolve()):
            raise ValueError(f"Generated filename would escape the vault directory: {filename!r}")

        # Build YAML frontmatter for Obsidian Dataview compatibility.
        duration_min = int(duration_seconds / 60)
        frontmatter = {
            "title": summary.title,
            "date": date_str,
            "time": time_str.replace("-", ":"),
            "duration_minutes": duration_min,
            "word_count": transcript.word_count,
            "tags": summary.tags,
            "type": "meeting-note",
        }
        frontmatter_yaml = _yaml.dump(
            frontmatter, default_flow_style=False, allow_unicode=True
        ).rstrip()

        content_parts = [
            "---",
            frontmatter_yaml,
            "---",
            "",
            summary.raw_markdown,
            "",
            "---",
            "",
            (
                f"*Generated by MeetingMind on "
                f"{time.strftime('%Y-%m-%d %H:%M')} — "
                f"{duration_min} min, {transcript.word_count:,} words*"
            ),
        ]

        if self._config.include_full_transcript:
            content_parts.extend(
                [
                    "",
                    "---",
                    "",
                    "## Full Transcript",
                    "",
                ]
            )
            for seg in transcript.segments:
                timestamp = f"**{seg.timestamp}**"
                speaker = f" *{seg.speaker}*:" if seg.speaker else ""
                content_parts.append(f"{timestamp}{speaker} {seg.text.strip()}")
                content_parts.append("")

        content = "\n".join(content_parts)
        filepath.write_text(content, encoding="utf-8")

        logger.info("Markdown written: %s", filepath)
        return filepath
