"""
Markdown output writer for Obsidian-compatible vaults.

Produces a single .md file per meeting containing YAML frontmatter
(for Obsidian Dataview queries), the AI-generated summary, and
optionally the full timestamped transcript.

File naming uses the configured template with date and a slug
derived from the meeting title.
"""

import logging
import os
import time
from pathlib import Path

from slugify import slugify

from src.summariser import MeetingSummary
from src.transcriber import Transcript
from src.utils.config import MarkdownConfig

logger = logging.getLogger(__name__)


class MarkdownWriter:
    """Writes meeting output to an Obsidian-compatible Markdown vault."""

    def __init__(self, config: MarkdownConfig):
        self._config = config

    def write(
        self,
        summary: MeetingSummary,
        transcript: Transcript,
        started_at: float,
        duration_seconds: float,
    ) -> Path:
        """
        Write the meeting summary and transcript to a .md file.

        Returns the path to the created file.
        """
        vault_path = Path(self._config.vault_path)
        os.makedirs(vault_path, exist_ok=True)

        # Build the filename from the configured template.
        date_str = time.strftime("%Y-%m-%d", time.localtime(started_at))
        time_str = time.strftime("%H-%M", time.localtime(started_at))
        title_slug = slugify(summary.title, max_length=60)

        filename = self._config.filename_template.format(
            date=date_str,
            time=time_str,
            slug=title_slug or "meeting",
        )
        filepath = vault_path / filename

        # Build YAML frontmatter for Obsidian Dataview compatibility.
        tags_yaml = ", ".join(f'"{t}"' for t in summary.tags)
        duration_min = int(duration_seconds / 60)

        content_parts = [
            "---",
            f"title: \"{summary.title}\"",
            f"date: {date_str}",
            f"time: {time_str.replace('-', ':')}",
            f"duration_minutes: {duration_min}",
            f"tags: [{tags_yaml}]",
            f"type: meeting-note",
            "---",
            "",
            summary.raw_markdown,
            "",
            "---",
            "",
            f"*Generated by MeetingMind on {time.strftime('%Y-%m-%d %H:%M')}*",
        ]

        if self._config.include_full_transcript:
            content_parts.extend([
                "",
                "---",
                "",
                "## Full Transcript",
                "",
                "```",
                transcript.timestamped_text,
                "```",
            ])

        content = "\n".join(content_parts)
        filepath.write_text(content, encoding="utf-8")

        logger.info(f"Markdown written: {filepath}")
        return filepath
